spring:
  application:
    name: learningApp

  main:
    banner-mode: off
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379

  data:
    elasticsearch:
      repositories:
        enabled: true
      mapping:
        exclude-class: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: ${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA:always}
    platform: ${SPRING_BATCH_PLATFORM:postgresql}

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    consumer:
      group-id: user-learning-progress-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: record

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: ${VNPAY_URL}
  return-url: ${VNPAY_RETURN_URL}
    

aws:
  iam-nam:
    access-key: ${AWS_ACCESS_KEY_NAM}
    secret-key: ${AWS_SECRET_KEY_NAM}
  region: ${AWS_REGION}
  region-nam: ${AWS_REGION_NAM}
  cognito:
    cognito-domain: ${AWS_COGNITO_DOMAIN}
    client-id: ${AWS_CLIENT_ID}
    client-secret: ${AWS_CLIENT_SECRET}
    user-pool-id: ${AWS_USER_POOL_ID}
  iam:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
    bucket-nam: ${AWS_S3_BUCKET_NAME_V2}
google:
#  redirect-uri: ${REDICT_URI}
  api-key: ${GOOGLE_API_KEY}
gemini:
  api-key: ${GEMINI_API_KEY}

jwt:
  secret-key: ${JWT_SECRET}

app:
  admin:
    email: ${ADMIN_EMAIL}
    full-name: ${ADMIN_FULL_NAME}
    role: ${ADMIN_ROLE}
    password: ${ADMIN_PASSWORD}

