name: Docker Image CI

on:
  push:
    branches: [ "production" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./learningApp
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
